CC = gcc
CFLAGS = -g -Wall -o
DEPS = 
OBJECTS =
EXECS = time-syscall

all:
	$(CC) $(CFLAGS) time-syscall time-syscall.c $(OBJECTS) 
	$(CC) $(CFLAGS) time-signal time-signal.c $(OBJECTS) 



clean:
	rm *.o $(EXECS)